{% set name = "atomman" %}
{% set version = "1.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b0943beffb2c789cfef668b66feca010da6192c72c056d6a8819d79339dade68
  patches:
    - setup.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<=37 or python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
  run:
    - python
    - pip
    - ase
    - pymatgen
    - phonopy
    - xmltodict
    - datamodeldict
    - numpy >=1.15
    - matplotlib-base
    - scipy
    - pandas
    - cython
    - numericalunits
    - toolz
    - potentials >=0.3.6

test:
  imports:
    - atomman
  commands:
    - pip check

about:
  home: https://github.com/usnistgov/atomman
  license: NIST-PD
  license_file: LICENSE.TXT
  summary: Atomistic Manipulation Toolkit

  description: |
    atomMan: the Atomistic Manipulation Toolkit is a Python library for 
    creating, representing, manipulating, and analyzing large-scale atomic 
    systems of atoms. The focus of the package is to facilitate the rapid 
    design and development of simulations that are fully documented and 
    easily adaptable to new potentials, configurations, etc. 
  doc_url: https://www.ctcms.nist.gov/potentials/atomman/
  dev_url: https://github.com/usnistgov/atomman

extra:
  recipe-maintainers:
    - jan-janssen
    - lmhale99
