{% set name = "atomman" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 840acea340f13a379589f5c457e8b733a4087df581aff3ac6823bcb0ba1419dd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [python < 3.7]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
  run:
    - python
    - pip
    - xmltodict
    - datamodeldict
    - numpy >=1.15
    - matplotlib-base
    - scipy
    - pandas
    - cython
    - numericalunits
    - toolz

test:
  imports:
    - atomman
  commands:
    - pip check

about:
  home: https://github.com/usnistgov/atomman
  license: OTHER
  license_family: OTHER
  license_file: LICENSE.TXT
  summary: Atomistic Manipulation Toolkit

  description: |
    atomMan: the Atomistic Manipulation Toolkit is a Python library for 
    creating, representing, manipulating, and analyzing large-scale atomic 
    systems of atoms. The focus of the package is to facilitate the rapid 
    design and development of simulations that are fully documented and 
    easily adaptable to new potentials, configurations, etc. 
  doc_url: https://github.com/usnistgov/atomman
  dev_url: https://github.com/usnistgov/atomman

extra:
  recipe-maintainers:
    - jan-janssen
    - lmhale99
