{% set name = "atomman" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 98ab612644e1c89dd1f6a9747977ca78117e2430b18a763887cf433526f73ee0

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
  run:
    - python
    - xmltodict
    - datamodeldict
    - numpy >=1.15 
    - matplotlib
    - scipy
    - pandas
    - cython
    - numericalunits
    - toolz

test:
  imports:
    - atomman

about:
  home: https://github.com/usnistgov/atomman
  license: OTHER
  license_family: OTHER
  license_file: LICENSE.TXT
  summary: 'Atomistic Manipulation Toolkit'

  description: |
    atomMan: the Atomistic Manipulation Toolkit is a Python library for 
    creating, representing, manipulating, and analyzing large-scale atomic 
    systems of atoms. The focus of the package is to facilitate the rapid 
    design and development of simulations that are fully documented and 
    easily adaptable to new potentials, configurations, etc. 
  doc_url: https://github.com/usnistgov/atomman
  dev_url: https://github.com/usnistgov/atomman

extra:
  recipe-maintainers:
    - jan-janssen
    - lmhale99
