travis:
  secure:
    BINSTAR_TOKEN: U6qiX2fNM+bbcU6QaVuR4f1bCieEASr+/t6l8Dy9CyXBVfKgYdAANULELL38nr8oHpSngoqbHxqtd7DHpIyyw7pDhj9t7fftb6TKjID9c1T4gitMmwV4xgpiGDFLpxu5ejhRekHUx65rAny+uYvmiJ0KgT90C4fnFVEKHcEaAq+CidVlyrM+mKtax7h7r3WN7cba5wBiPMFEqgrMmfXJZmsUceWkTajk0w4j429uC4vufCDoPJYMU3nzJWTMO/CVu0JuRQUHFIG8tTXFyeaa2wrsU9u2PHR8UXSsnw3zF3pArW6cPDRud+EyGOV5KwIzuza3mjBMzN1h6jcXsHUKFTCqiZX+NVbBjCtcx/lPBVZN61zKs1HodfGWnd+82pKV0HpKrcXR3W8vNHrBI4S8weXxqessxF5DtbOquTlUAaXGyO8Ine7JAQl/6VB1b2zDKBShz1Q9KAPmS/HcYiIRRmyXB6UqZT9UJ52Mb2JN6GK0Vw8BT9hh1jgyg6aPA8pqEN1YzAug2XP7fvvy+/by+gK004z5MKF1ypvx0STtlAIo4/L9hUMQb7aDgBipXhxam/mBqlNK0par9hO2Jh6C7GT/9hFy/1VJwYZYQIP2sPbe6CaoKgf0kMz7MSoZoVsYzleJKPIQuBANRuAR8AgCU64G3istJz9i2z1goTddrSw=
bot:
  automerge: true
conda_forge_output_validation: true
